# Peu de processus Apache : l'offre gratuite de Render n'a que 512 Mo de RAM
<IfModule mpm_prefork_module>
    StartServers             2
    MinSpareServers          2
    MaxSpareServers          4
    MaxRequestWorkers        12
    MaxConnectionsPerChild   500
</IfModule>
